"use strict";

const { AUTO_FIX_TYPES } = require("./audit");

const QUERIES = {
  findings: `SELECT f.id, f.product_id, f.issue_type, f.ingredient_ids, f.evidence, f.suggestion, f.product_data,
                    p.name AS product_name, f.brand_name
             FROM ai_jobs.product_audit_findings f JOIN public.products p ON p.id = f.product_id
             WHERE f.status = 'approved' ORDER BY f.product_id, f.id`,
  links: `SELECT product_id, ingredients_id FROM public.product_ingredients WHERE product_id = ANY($1::int[])`,
};

function sqlComment(value) {
  return String(value || "").replace(/[\r\n]+/g, " ").slice(0, 200);
}

function idList(ids) {
  return ids.map((id) => Number(id)).join(", ");
}

// Turns approved duplicate/extra ingredient findings into one transaction. Findings whose
// links changed since the audit are skipped with a comment; other approved findings need a
// human-entered value and are returned as manual work.
function buildFixSql(findings, linksByProduct) {
  const lines = [
    "-- Generated by besin-ai-jobs export-fixes. Review, then run in the Supabase SQL Editor.",
    "BEGIN;",
    "",
  ];
  const applied = [];
  const skipped = [];
  const manual = [];
  const products = new Set();

  for (const finding of findings) {
    if (!AUTO_FIX_TYPES.includes(finding.issue_type)) {
      manual.push(finding);
      continue;
    }
    const productId = Number(finding.product_id);
    const linked = linksByProduct.get(productId) || new Set();
    const ids = (finding.ingredient_ids || []).map(Number);
    const [keep, ...duplicates] = ids;
    const remove = finding.issue_type === "duplicate_ingredient" ? duplicates : ids;
    const header = `-- #${finding.id} product ${productId} ${sqlComment(finding.product_name)} (${finding.issue_type}): ${sqlComment(finding.evidence)}`;

    if (finding.issue_type === "duplicate_ingredient" && !linked.has(keep)) {
      skipped.push({ finding, reason: `ingredient ${keep} to keep is no longer linked` });
      lines.push(header, `-- SKIPPED: ingredient ${keep} to keep is no longer linked`, "");
      continue;
    }
    const stillLinked = remove.filter((id) => linked.has(id));
    if (!stillLinked.length) {
      skipped.push({ finding, reason: "the links to remove are already gone" });
      lines.push(header, "-- SKIPPED: the links to remove are already gone", "");
      continue;
    }

    lines.push(header);
    if (finding.issue_type === "duplicate_ingredient") {
      lines.push(
        `UPDATE public.product_ingredients keep_link SET percentage = source.percentage
FROM (SELECT percentage FROM public.product_ingredients
      WHERE product_id = ${productId} AND ingredients_id IN (${idList(stillLinked)}) AND percentage IS NOT NULL
      ORDER BY id LIMIT 1) source
WHERE keep_link.product_id = ${productId} AND keep_link.ingredients_id = ${keep} AND keep_link.percentage IS NULL;`,
        `INSERT INTO public.product_allergens (product_id, ingredient_id, is_trace)
SELECT product_id, ${keep}, bool_and(is_trace) FROM public.product_allergens
WHERE product_id = ${productId} AND ingredient_id IN (${idList(stillLinked)})
GROUP BY product_id
ON CONFLICT (product_id, ingredient_id) DO UPDATE SET is_trace = public.product_allergens.is_trace AND EXCLUDED.is_trace;`,
        `DELETE FROM public.product_allergens WHERE product_id = ${productId} AND ingredient_id IN (${idList(stillLinked)});`,
      );
    }
    lines.push(`DELETE FROM public.product_ingredients WHERE product_id = ${productId} AND ingredients_id IN (${idList(stillLinked)});`, "");
    applied.push(finding);
    products.add(productId);
  }

  for (const productId of [...products].sort((a, b) => a - b)) {
    lines.push(`SELECT * FROM public.calculate_product_score_new(${productId});`);
  }
  if (applied.length) {
    lines.push("", `UPDATE ai_jobs.product_audit_findings SET status = 'applied'
WHERE status = 'approved' AND id IN (${idList(applied.map((finding) => finding.id))});`);
  }
  lines.push("", "COMMIT;", "");
  return { sql: lines.join("\n"), applied, skipped, manual };
}

async function loadApprovedFindings(client) {
  const findings = (await client.query(QUERIES.findings)).rows;
  const productIds = [...new Set(findings.map((finding) => Number(finding.product_id)))];
  const linksByProduct = new Map(productIds.map((id) => [id, new Set()]));
  if (productIds.length) {
    for (const row of (await client.query(QUERIES.links, [productIds])).rows) {
      linksByProduct.get(Number(row.product_id)).add(Number(row.ingredients_id));
    }
  }
  return { findings, linksByProduct };
}

// Approved findings that need a human-entered value, one readable line each.
function manualList(findings) {
  if (!findings.length) return "";
  const line = (finding) => {
    const brand = finding.brand_name ? ` (${finding.brand_name})` : "";
    return `#${finding.id} · ürün ${finding.product_id} ${finding.product_name}${brand} · ${finding.issue_type}: `
      + `${finding.evidence} → ${finding.suggestion}`.replace(/[\r\n]+/g, " ");
  };
  return [
    "Düzelttikten sonra bulgunun status alanını applied yap.",
    ...findings.map(line),
  ].join("\n");
}

module.exports = { AUTO_FIX_TYPES, buildFixSql, loadApprovedFindings, manualList };
